-- MySQL Script generated by MySQL Workbench
-- Sat Jun  6 01:36:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema streaming
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `streaming` ;

-- -----------------------------------------------------
-- Schema streaming
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `streaming` DEFAULT CHARACTER SET utf8 ;
USE `streaming` ;

-- -----------------------------------------------------
-- Table `streaming`.`clasificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `streaming`.`clasificacion` ;

CREATE TABLE IF NOT EXISTS `streaming`.`clasificacion` (
  `idclasificacion` INT NOT NULL AUTO_INCREMENT,
  `clasificacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclasificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streaming`.`idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `streaming`.`idioma` ;

CREATE TABLE IF NOT EXISTS `streaming`.`idioma` (
  `ididioma` INT NOT NULL AUTO_INCREMENT,
  `idioma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ididioma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streaming`.`pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `streaming`.`pelicula` ;

CREATE TABLE IF NOT EXISTS `streaming`.`pelicula` (
  `idpelicula` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(90) NOT NULL,
  `idclasificacion` INT NOT NULL,
  `ididioma` INT NOT NULL,
  PRIMARY KEY (`idpelicula`),
  INDEX `fk_pelicula_clasificacion1_idx` (`idclasificacion` ASC),
  INDEX `fk_pelicula_idioma1_idx` (`ididioma` ASC),
  CONSTRAINT `fk_pelicula_clasificacion1`
    FOREIGN KEY (`idclasificacion`)
    REFERENCES `streaming`.`clasificacion` (`idclasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelicula_idioma1`
    FOREIGN KEY (`ididioma`)
    REFERENCES `streaming`.`idioma` (`ididioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streaming`.`programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `streaming`.`programa` ;

CREATE TABLE IF NOT EXISTS `streaming`.`programa` (
  `idprograma` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `temporadas` INT NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(90) NOT NULL,
  `idclasificacion` INT NOT NULL,
  `ididioma` INT NOT NULL,
  PRIMARY KEY (`idprograma`),
  INDEX `fk_programa_clasificacion1_idx` (`idclasificacion` ASC),
  INDEX `fk_programa_idioma1_idx` (`ididioma` ASC),
  CONSTRAINT `fk_programa_clasificacion1`
    FOREIGN KEY (`idclasificacion`)
    REFERENCES `streaming`.`clasificacion` (`idclasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programa_idioma1`
    FOREIGN KEY (`ididioma`)
    REFERENCES `streaming`.`idioma` (`ididioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streaming`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `streaming`.`usuario` ;

CREATE TABLE IF NOT EXISTS `streaming`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(60) NOT NULL,
  `ididioma` INT NOT NULL,
  `idclasificacion` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_idioma_idx` (`ididioma` ASC),
  INDEX `fk_usuario_clasificacion1_idx` (`idclasificacion` ASC),
  CONSTRAINT `fk_usuario_idioma`
    FOREIGN KEY (`ididioma`)
    REFERENCES `streaming`.`idioma` (`ididioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_clasificacion1`
    FOREIGN KEY (`idclasificacion`)
    REFERENCES `streaming`.`clasificacion` (`idclasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- INSERCIONES 

start transaction;

insert into idioma(idioma) values ("Español"),
("Inglés"),("Francés"),("Alemán"),("Coreano"),("Japonés"),("Chino");

insert into clasificacion(clasificacion) values("AA"),("A"),("B15"),("C"),("D");

insert into usuario(nombre,foto,ididioma,idclasificacion) 
values("Alejandro","C:/xampp/htdocs/Proyecto-Tecnologias-web/Crear_perfil/fotos/image06033419.jpg",4,4);

insert into pelicula(nombre,duracion,genero,imagen,ididioma,idclasificacion) 
values("Hancock","1 h 32 min","Fantasía, Comedia","C:/xampp/htdocs/Proyecto-Tecnologias-web/streaminghancock.jpg",2,3),
("Harry Potter","2 h 25 min","Fantasía","C:/xampp/htdocs/Proyecto-Tecnologias-web/harrypotter.jpg",2,1),
("Las crónicas de Narnia: el león, la bruja y el ropero","1 h 15 min","Fantasía","C:/xampp/htdocs/Proyecto-Tecnologias-web/narnia.jpg",2,1),
("Up: Una aventura de altura","1 h 02 min","Fantasía","C:/xampp/htdocs/Proyecto-Tecnologias-web/up.jpg",1,1),
("Shrek","1 h 14 min","Fantasía, Comedia","C:/xampp/htdocs/Proyecto-Tecnologias-web/shrek.jpg",2,2),
("White chicks","1 h 20 min","Comedia","C:/xampp/htdocs/Proyecto-Tecnologias-web/whitechicks.jpg",2,2),
("How to be single","1 h 35 min","Romance","C:/xampp/htdocs/Proyecto-Tecnologias-web/howtobesingle.jpg",2,3),
("Toy Story","1 h 01 min","Fantasía","C:/xampp/htdocs/Proyecto-Tecnologias-web/toystory.jpg",1,1),
("The ugly truth","1 h 36 min","Comedia romántica","C:/xampp/htdocs/Proyecto-Tecnologias-web/theuglythruth.gif",2,3),
("10 cosas que odio de ti","1 h 24 min","Romance","C:/xampp/htdocs/Proyecto-Tecnologias-web/10things.jpg",1,2);

insert into programa(nombre,temporadas,genero,imagen,ididioma,idclasificacion)
values("How I met you mother","8","Comedia","C:/xampp/htdocs/Proyecto-Tecnologias-web/howimet.png",2,3),
("Dark","2","Drama,Ficción","C:/xampp/htdocs/Proyecto-Tecnologias-web/dark.jpg",2,3),
("The Good Doctor","7","Drama médico","C:/xampp/htdocs/Proyecto-Tecnologias-web/thegooddoctor.jpg",2,2),
("Escandalosos","2","Animación","C:/xampp/htdocs/Proyecto-Tecnologias-web/escandalosos.jpg",1,1),
("Game of Thrones","8","Drama","C:/xampp/htdocs/Proyecto-Tecnologias-web/gameofthrones.jpg",2,3),
("Grey's Anatomy","15","Drama","C:/xampp/htdocs/Proyecto-Tecnologias-web/grey.jpg",2,3),
("Pretty little liers","7","Misterio","C:/xampp/htdocs/Proyecto-Tecnologias-web/prettyLittleLiars.jpeg",2,2),
("Boys Over Flowers","1","Drama,Romance","C:/xampp/htdocs/Proyecto-Tecnologias-web/boysoverflowers.jpg",2,2),
("Club de cuervos","4","Comedia","C:/xampp/htdocs/Proyecto-Tecnologias-web/club.jpg",2,3),
("Dr. House","8","Drama","C:/xampp/htdocs/Proyecto-Tecnologias-web/house.jpg",2,2);

commit;